#!/bin/sh

INDEXDIR="/home/orchidhippo5/www/stg-connect/_cms"
if [ -z "${INDEXDIR}" ]; then exit 0; fi

case $2 in
POST-DEINSTALL)
	if [ -d "${INDEXDIR}" ]; then
		rm -fr "${INDEXDIR}" 2>/dev/null || true
	fi
	;;
esac
exit 0
